### ISSUE TITLE
Instrumentation doesn't work on production builds in AWS Amplify

### ISSUE THREAD

**Issue by Akhilesh-aarzoo** [newrelic/newrelic-node-nextjs#91] opened 2022-10-18 20:53 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

 I have configured new relic in my NextJs application, it works from my local (can see metrics on the dashboard), but when I deploy the application on AWS Amplify, I am not getting any metrics.

## Expected Behavior
Should be receiving the metrics on production

## Steps to Reproduce
I have followed the "Frontend Observability" section of this https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data for setting up client-side monitoring

## Your Environment
package.json
<img width="492" alt="Screenshot 2022-10-19 at 2 18 15 AM" src="https://user-images.githubusercontent.com/63853554/196541656-89d54ef6-c4a5-4cf2-a40b-afc0fc369eda.png">
MyDocument
<img width="610" alt="Screenshot 2022-10-19 at 2 21 02 AM" src="https://user-images.githubusercontent.com/63853554/196542206-e7c939fe-fdaf-45a6-b4fb-efa71bb057d1.png">
<img width="624" alt="Screenshot 2022-10-19 at 2 21 36 AM" src="https://user-images.githubusercontent.com/63853554/196542293-bb389e2c-6df0-45f2-9b2d-2c5292eeba5c.png">

* ex: Browser name and version:
* ex: Node version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bizob2828** [comment] 2022-10-18 20:55
Closing as a duplicate of #88 and/or https://issues.newrelic.com/browse/NEWRELIC-4467.  We do not support Amplify and Next.js at the moment

**Closed by bizob2828** 2022-10-18 20:55 UTC
Labels: bug, needs-triage

**Comment by Akhilesh-aarzoo** [comment] 2022-10-19 06:13
@bizob2828 - Thanks for the reply. Can you point me to the link where I can vote for this feature? The JIRA ticket you shared doesn't open for me.

**Comment by bizob2828** [comment] 2022-10-20 15:56
@Akhilesh-aarzoo I've been told the voting won't be available until april of next year 😬 .  I can just upvote it for you
