### ISSUE TITLE
Production build does not recognize _document transaction and does not inject NR script

### ISSUE THREAD

**Issue by creativeux** [newrelic/newrelic-node-nextjs#103] opened 2022-12-15 19:40 UTC
## Description

I know there is a lot of discussion around the dreaded `<!-- NREUM: (1) -->` injection caused by invoking the New Relic browser injection script outside the context of a transaction -- I have read what I think is all of the discussion on the topic at this point -- and I created a public discussion topic, but I wanted to open an issue as well because I feel that this is either a bug or a documentation gap.

## Expected Behavior

The dev and prod builds should behave the same with the appropriate New Relic scripts injected into the `<head>` block.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

When I clone the [newrelic-experimental/newrelic-nextjs-integration](https://github.com/newrelic-experimental/newrelic-nextjs-integration) repository and run it as-is, I see a difference between the dynamic `<head>` injection in `npm run dev` mode and after running `npm run build` and `npm start` against the built assets. In "dev mode", everything appears to work correctly and the browser module successfully reports metrics and errors to New Relic. In "prod mode", the server side successfully injects the script content from `browserTimingHeader`, but when it is evaluated, the <script> block contains the `<!-- NREUM: (1) -->` output rather than the necessary scripts.

## Steps to Reproduce

1. Clone [this repository](https://github.com/newrelic-experimental/newrelic-nextjs-integration) and install dependencies (`npm i`)
2. Remove the dependency on localhost for blog API (I used `const data = { json: () => [] };` to bypass the API calls).
3. Update license key and app name (either via env vars or `newrelic.js`)
4. Run `npm run dev` and inspect the `<head>` for the index page. You will see the correct `<script>` injection.
5. Run `npm run build` to generate a production build
6. Run `npm start` and inspect the `<head>` again -- you will see `<!-- NREUM: (1) -->`.

## Your Environment

Mac OSX 12.5, Node 16.15.1, npm 8.11.0

To eliminate versions as variables here, I upgraded my versions (and associated types/devDependencies) to the latest at the time of creating this issue with no effect on the results. Here is where I ended up:
```
 "dependencies": {
    "@newrelic/next": "^0.3.1",
    "express": "^4.17.1",
    "newrelic": "9.7.3",
    "next": "13.0.6",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "winston": "^3.8.1"
  },
```

## Additional context

Public discussion thread [here](https://discuss.newrelic.com/t/nextjs-integration-works-in-dev-mode-but-not-in-prod-mode/191865).

I've been able to reproduce this with the example repo here as well as in our custom NextJS app. Identical behavior in both places. We have spent time exploring the impact of static page optimization, and my hunch is that there is some connection between NextJS's static optimization and how the New Relic init script determines what is a "transaction" from within the `_document.tsx` `getInitialProps` injection on initial load of the index page. Perhaps something about NextJS's static generation is conflicting with New Relic's transaction detection?

Is this integration still a valid approach? Is it possible that I'm missing a configuration step? Please let me know how I can support!

**Comment by bizob2828** [comment] 2022-12-15 20:08
@creativeux is it all pages or just static pages? There is a limitation of this method on static pages and I explain it more https://github.com/newrelic/newrelic-node-nextjs/issues/103.  We're trying to understand why we have this limitation of being in transaction context.

**Comment by creativeux** [comment] 2022-12-15 20:23
@bizob2828 I _think_ it's just static pages. For the `index.tsx` in the example repo, if I simply add an empty `getServerSideProps` block, it starts to work.

```
export const getServerSideProps = async () => ({ props: {} });
```

I checked with others on the team and they have found that switching `getStaticProps` to `getServerSideProps` where we are pulling in i18next locales makes things work as well.

The tough part about this is that NextJS determines whether or not a page is static. I'm somewhat of a noob with NextJS, so there might be a configuration that we need to set to disable static optimization until this is resolved, but would love to be able to take advantage of static pages eventually.

**Comment by bizob2828** [comment] 2022-12-15 20:56
@creativeux ok yea we are aware of this issue. It is a duplicate of #99. For now you can follow the [copy paste method](https://docs.newrelic.com/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent/) of injecting browser agent.  I'm sorry for the inconvenience this creates but we're trying to get this work prioritized by our PM

**Closed by bizob2828** 2022-12-15 20:56 UTC
Labels: bug, needs-triage

**Comment by greenymcgee** [comment] 2023-01-20 19:47
@bizob2828 can you provide an example of how to use the copy paste method within a NextJS repo? I've seen this option mentioned in several threads, but I don't know of a way to use this method with NextJS.

**Comment by jordigh** [comment] 2023-01-20 20:06
@greenymcgee The method provided by the latest version of the agent as described by this PR might be helpful.

https://github.com/newrelic/node-newrelic/pull/1475

**Comment by bizob2828** [comment] 2023-01-20 20:18
Which to be clear @greenymcgee eliminates the means of the copy paste method.  We enhanced our api to get the browser timing header to support this SSG use case

**Comment by greenymcgee** [comment] 2023-01-20 20:29
@bizob2828 you just made my day 🙌 . I've been fighting with this for days
