### ISSUE TITLE
EKS POD build fails when enable RUM monitoring (_document.tsx)

### ISSUE THREAD

**Issue by ranga0001** [newrelic/newrelic-node-nextjs#159] opened 2023-09-13 13:53 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

whenever enable RUM for Nextjs .pod build fails with  error

kubectl logs -f -ndev platform-service-85f8cb46b4-7z48j
node:internal/modules/cjs/loader:1029
  throw err;
  ^
Error: Cannot find module 'cross-fetch'
Require stack:
- /var/www/html/app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at Module.Hook._require.Module.require (/var/www/html/node_modules/require-in-the-middle/index.js:167:34)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/var/www/html/app.js:1:542)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/var/www/html/app.js' ]

My Dockerfile content as follow

WORKDIR /var/www/html
    
COPY ./package.json ./package-lock.json ./
COPY ./dist/apps/platform-service/ ./
COPY ./node_modules/ ./node_modules/

RUN npm install newrelic

ENV NEW_RELIC_APP_NAME="dev-test-app" \
    NEW_RELIC_LICENSE_KEY="xxxxx" \
	NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true \
    NEW_RELIC_LOG=stdout \
    NEW_RELIC_APPLICATION_LOGGING_ENABLED=false \
    NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=false \
    NEW_RELIC_ALLOW_ALL_HEADERS=true \
    NEW_RELIC_LOG_ENABLED=true \
    NEW_RELIC_LOG_LEVEL=info \
    NEW_RELIC_ATTRIBUTES_EXCLUDE='["request.headers.cookie", "request.headers.authorization", "request.headers.proxyAuthorization", "request.headers.setCookie*", "request.headers.x*", "response.headers.cookie", "response.headers.authorization", "response.headers.proxyAuthorization", "response.headers.setCookie*", "response.headers.x*"]'
#    NODE_OPTIONS="--require @newrelic/next"

EXPOSE 3000

CMD ["node", "-r", "newrelic", "--enable-source-maps", "./app.js"]

**Comment by bizob2828** [comment] 2023-09-13 14:15
@ranga0001 I'm not sure this is related to the `@newrelic/next` instrumentation.  I don't see that listed in the dependency tree. I also notice in your Dockerfile you're only installing `newrelic` and not `@newrelic/next`.  If you can provide a reproduction case, that'll be helpful

**Comment by ranga0001** [comment] 2023-09-13 19:55
it pointing to _document.tsx and fails to create pod
./pages/_document.tsx:24:6
Type error: Type '{ browserTimingHeader: any; html: string; head?: (JSX.Element | null)[] | undefined; styles?: JSX.Element | ReactFragment | ReactElement<any, string | JSXElementConstructor<any>>[] | undefined; }' is not assignable to type 'DocumentInitialProps'.
  Object literal may only specify known properties, and 'browserTimingHeader' does not exist in type 'DocumentInitialProps'.

**Comment by bizob2828** [comment] 2023-09-13 20:12
@ranga0001 We have an example of how to inject browser agent in this [sample Next.js app](https://github.com/newrelic-experimental/newrelic-nextjs-integration/blob/main/pages/_document.tsx)

**Comment by ranga0001** [comment] 2023-09-21 18:21
Frontend Monitoring start working once we added  "ENV NEW_RELIC_APP_NAME="dev-test-app  and 
NEW_RELIC_LICENSE_KEY="xxxxx" into build script. 
Middleware Monitoring working when we enable these 2 variable in Dockerfile (during runtime). 
however js Snippet   injection  happens during page build stage .if we dont pass 2 variables it fails

Now the problem  what we are facing is 

Javascript snippet injection happens during build stage so whatever value we supply using Dockerfile runtime (dynamic variable ) not affecting browser monitoring Application name and account id.It become static value.however we are using common  build env variable file which is used for 3  different  environment  & application .so no way to alter browser app name dynamically

so no way to classify different  application and env.your help much appreciated .this is big blocker for application onboard to new relic 

Thanks in advance

Ranga

**Comment by bizob2828** [comment] 2023-09-21 18:40
@ranga0001 I'm not clear on the issue you're facing.  Have you looked at our [Next.js example app](https://github.com/newrelic-experimental/newrelic-nextjs-integration/blob/main/pages/_document.tsx)? It shows how to inject the browser agent. 

Also for issues that are in depth like this, without a reproduction case, I recommend leveraging our support team over at https://support.newrelic.com which can help deep-dive into solving the problem. They will also ask to collect the necessary information which may or may not be sensitive (such as logs).

**Comment by ranga0001** [comment] 2023-09-21 20:15
HI @bizob2828 
Thanks for your feedback. We are working with New Relic support to resolve this issue.(Case #00152060) .New Relic support also recommended to reach out to this form to see someone have workaround for it 

Application which is running using Next JS needs to build ( render page content from S3 ) and page during build stage.that stage itself Java Script snippet injection also happening .but Dockerfile ENV variable come into picture during runtime.So i need to pass below value in Dockerfile for Middleware agent monitoring
ENV NEW_RELIC_APP_NAME="dev-test" \
    NEW_RELIC_LICENSE_KEY="xxx" 

and add below 2 variable in build script for browser monitoring 

export NEW_RELIC_APP_NAME="browser-app" \
       NEW_RELIC_LICENSE_KEY="xxxx"

but build script is static and shared with 3 different  application 
if i dont pass this value during build browser monitoring fails and pod also crashing 

Thanks
Ranga

**Comment by bizob2828** [comment] 2023-09-21 21:01
Hmm, yea that's a tough one.  I would think you would have to build for all different deployment environments to properly get this set up.  This is just due to the limitations of how Next.js bundles code.

**Comment by bizob2828** [comment] 2023-10-09 17:28
I'm going to close this since you are working through our support staff.

**Closed by bizob2828** 2023-10-09 17:28 UTC
Labels: bug, needs-triage
