### ISSUE TITLE
New relic Nest JS instrumentation fails

### ISSUE THREAD

**Issue by ranga0001** [newrelic/newrelic-node-nextjs#161] opened 2023-09-13 20:47 UTC
## Description

NEST JS new relic instrumentation fails 

kubectl logs -f -ndev platform-service-85f8cb46b4-7z48j
node:internal/modules/cjs/loader:1029
  throw err;
  ^
Error: Cannot find module 'cross-fetch'
Require stack:
- /var/www/html/app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at Module.Hook._require.Module.require (/var/www/html/node_modules/require-in-the-middle/index.js:167:34)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/var/www/html/app.js:1:542)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/var/www/html/app.js' ]

dockerfile
WORKDIR /var/www/html
    
COPY ./package.json ./package-lock.json ./
COPY ./dist/apps/platform-service/ ./
COPY ./node_modules/ ./node_modules/

RUN npm install newrelic

ENV NEW_RELIC_APP_NAME="dev-test-xx-xxxx-service" \
    NEW_RELIC_LICENSE_KEY="xxxxxx" \
	NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true \
    NEW_RELIC_LOG=stdout \
    NEW_RELIC_APPLICATION_LOGGING_ENABLED=false \
    NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=false \
    NEW_RELIC_ALLOW_ALL_HEADERS=true \
    NEW_RELIC_LOG_ENABLED=true \
    NEW_RELIC_LOG_LEVEL=info \
    NEW_RELIC_ATTRIBUTES_EXCLUDE='["request.headers.cookie", "request.headers.authorization", "request.headers.proxyAuthorization", "request.headers.setCookie*", "request.headers.x*", "response.headers.cookie", "response.headers.authorization", "response.headers.proxyAuthorization", "response.headers.setCookie*", "response.headers.x*"]'

EXPOSE 3000

CMD ["node", "-r", "newrelic", "--enable-source-maps", "./app.js"]

**Comment by bizob2828** [comment] 2023-09-13 21:02
@ranga0001 this is a duplicate of #160.

**Closed by bizob2828** 2023-09-13 21:02 UTC
Labels: bug, needs-triage

**Comment by coreyarnold** [comment] 2023-09-15 17:46
@ranga0001 could you reach out to me (Engineering Manager for Node.js agent team) via email (carnold@newrelic.com)?
