### ISSUE TITLE
NextJS SSR pages deployed in vercel do not attach newrelic agent to page.

### ISSUE THREAD

**Issue by NathanHynes** [newrelic/newrelic-node-nextjs#163] opened 2023-09-25 18:05 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
 I have been following the guide that you have provided here in order to setup your agent to monitor a nextJS app. https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data#toc-next-steps

Everything seems to work correctly locally on all pages. 

However when deploying the pages through vercel I can see that the newrelic script isnt injected into pages which are using `getServerSideProps`. On pages where I am not specifying this it seems to work as expected. I can even log in the browser console `newrelic.info`. This doesn't seem to be the case for getServerSideProps pages. 

Looking at your nextJS repo attached to the guide I even instrumented this code:
```
if (!newrelic.agent.collector.isConnected()) {
      console.log("newrelic needs connecting");
      await new Promise((resolve) => {
        console.log("hello?");
        newrelic.agent.on("connected", resolve);
      });
    }
```

However this hasn't helped.

On SSR pages when inspecting the script tag in the head I see `<!-- NREUM: (4) -->`, What does this mean? 

## Expected Behavior
For the app to run the same both locally and when deployed to Vercel

## Steps to Reproduce
Deploy your sample app to Vercel and see same results.

**Comment by mrickard** [comment] 2023-09-25 18:11
@NathanHynes This is very likely a duplicate of this issue: https://github.com/newrelic/newrelic-node-nextjs/issues/135

We have a roadmap item for working with Vercel and similar cloud providers. (The above issue discusses a remediation, but that method wouldn't work with Vercel.)

**Comment by NathanHynes** [comment] 2023-09-26 08:08
Thanks @mrickard is there any guidance/docs on the best setup for newRelic and NextJs apps deployed through Vercel?

There seems to be a lot of documentation on your site around Newrelic and Next with contradict each other. 

The solutions on offer are
- script snippet
- NewRelic vercel integration plugin
- newrelic-node-nextjs agent

If I have a project setup utilising the API service NextJs has alongside data-fetching techniques such as getServerSideProps what is the current best set up to
- monitor frontend metrics
- monitor errors both server side and client side
- monitor next API metrics
- monito next API errors

Also what does this error mean `<!-- NREUM: (4) -->` ?

Thank you for your help

**Comment by mrickard** [comment] 2023-09-26 14:35
@NathanHynes We've not been able to give reliable guidance on the best setup for New Relic and NextJs in Vercel. It's under active investigation (including a PR into Next two weeks ago), but once deployed in Vercel's hosting environment, there are multiple conditions that interfere with instrumentation. We don't have a lot of information yet. 

I can say that `<!-- NREUM: (4) -->` is the error code you'll see when an application attempts to inject the New Relic browser agent, but the New Relic Node Agent is unable to get an application ID. This typically will happen if the `getBrowserTimingHeader` method isn't being called from within the context of a transaction--that's the case with server-side rendering. [In v9.8.0](https://docs.newrelic.com/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-8-0/) we added the `allowTransactionlessInjection` option to allow for the browser agent to be injected during SSR. 

We are still working on compatibility with Vercel.

**Closed** 2023-10-10 19:55 UTC
Labels: duplicate
